---
name: Test Pycpp Module
on: push
jobs:
  mac-test-module:
    name: Mac Test Module
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v2

      - name: Install prereqs
        run: brew install swig

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

      - name: Generate library file
        name: ./gen_lib

      - name: Run tests
        run: pipenv run test -v

  ubuntu-test-module:
    name: Ubuntu Test Module
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Install prereqs
        run: apt install -y swig g++

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

      - name: Generate library file
        name: ./gen_lib

      - name: Run tests
        run: pipenv run test -v
